#!/usr/bin/env bash
# PineNote input methods: pinyin (traditional output) and Japanese (romaji), both on IBus.
#
# 🔴 IBus, not fcitx5. This is not a preference.
#    There is no physical keyboard here. The primary input device is the pn-osk on-screen
#    keyboard, which patches GNOME Shell's own Keyboard class (it imports
#    resource:///org/gnome/shell/ui/keyboard.js). The OSK commits through Clutter
#    InputMethod to IBus. fcitx5 draws its own candidate window and never sees those keys.
#
# 🔴 RIME, not libpinyin.
#    libpinyin's traditional output is a simplified lexicon with an OpenCC pass on the
#    end. One-simplified-to-many-traditional has to guess (發/髮, 乾/幹/干, 麵/面, 後/后).
#    RIME's luna_pinyin dictionary is already traditional, and simplified is the
#    converted direction (via the simplification switch). There is nothing to guess.
#
#    It uses the _tw variant: the vocabulary in
#    /usr/share/rime-data/luna_pinyin.dict.yaml leans towards Taiwan (軟體 is present
#    and 軟件 is not; 網路 seven times and 網絡 zero). The _tw variant layers t2tw
#    on top for Taiwan glyph forms (裡/裏, 著/着, 為/爲). The device's opencc lacks
#    t2twp.json, but the vocabulary layer did not need it anyway.
#
# 🔴 Mozc, not RIME's Japanese schema.
#    RIME's kana-to-kanji conversion is weak. Mozc has real phrase conversion and
#    learning. Both engines share one IBus and are switched via pn-panel's pn-input.
#
# The layout does not change: pinyin, romaji, and English consume the same 26 letters.
# Both engines declare layout=default to ibus, and pn-osk's _composeLayout catches
# them with its fall-through to `${groupName}-extended` → `us-extended`. The k6
# layout keeps its shape across source switches. That fallback makes this work.
set -euo pipefail

echo "== [1] Packages =="
# Simulate first. gnome-shell on this device was held by apt-mark (see setup.sh [4]),
# and "0 to remove" is the only guarantee worth trusting. Measured, this line only
# upgrades libibus 1.5.31→1.5.32. gnome-shell and mutter are left alone.
sudo apt-get install -s ibus ibus-rime ibus-mozc fonts-noto-cjk \
  | grep -E "^[0-9]+ upgraded|^Remv" || true
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
  ibus ibus-rime ibus-mozc fonts-noto-cjk

# fonts-noto-cjk is not optional. The device ships with only Droid Sans Fallback,
# so candidates would draw with fallback glyphs. CJK is readable at 227dpi;
# it only needed the fonts.

echo "== [2] RIME: Luna Pinyin, Traditional Taiwan =="
mkdir -p "$HOME/.config/ibus/rime"
cat > "$HOME/.config/ibus/rime/default.custom.yaml" <<'EOF'
# Generated by setup/ime.sh. The reasons live in that script; only the two rules
# tied to this hardware remain here.
#
# page_size 5 — RIME's default. Changed once, then changed back.
#
# 🔴 It was 9 (2026-08-17). The reason was that k6 has a full number row, so nine
#    candidates could be selected directly by digits. The reason was right, but it lost
#    to something else: the horizontal candidate strip has 936 logical pixels of width,
#    and pinyin is typed in full sentences. When the first candidate is sentence-length,
#    nine cells do not fit. St falls back to ellipsizing every cell to "1 ...",
#    pushing the page arrows entirely out of view. This is arithmetic, not layout:
#    nine candidates with a long sentence cannot fit into 936 pixels no matter the
#    alignment. macOS gives the first candidate the space it needs, fits what it can
#    of the rest, and pages the overflow. page_size 5 moves in that direction. 1-5
#    are still selected by digits; 6-9 cost a page turn.
#
# 🔴 Candidates take two paths, and they select differently. In the device's actual
#    ibusCandidatePopup.js, _updateVisibility() reads:
#        isVisible = !Main.keyboard.visible && (...)
#    The floating window does not appear when the OSK is visible. Candidates are instead
#    passed to the OSK's top suggestions strip via Main.keyboard.addSuggestion(). That
#    method carries no index (indexes only go to the floating window), so the OSK strip
#    must be tapped; digits do nothing. (pn-osk has already removed that condition and
#    made the floating window serve both states, see its _pnDockCandidatePopup. This
#    note remains because it explains why that patch exists.)
#
# schema_list is deliberately narrowed to one. RIME switches schemas with Ctrl+`; the
# k6 portrait topRow is "1234567890-=" and has no backtick (landscape has
# "`1234567890-="). Do not depend on a key that vanishes when the tablet rotates.
patch:
  # 🔴 Exactly two. Bopomofo goes through RIME, not chewing. RIME shows candidates as
  #    you type (same engine, same strip, same dictionary as pinyin), while chewing
  #    waits for space. pn-input's cycle unrolls the rime source into two faces,
  #    pinyin and bopomofo. Switching faces sends the F7/F8 keys bound below.
  schema_list:
    - schema: luna_pinyin_tw
    - schema: bopomofo_tw
  menu/page_size: 5
  # The menu follows schema_list order, not MRU (for manual F4; pn-input bypasses it).
  switcher/fix_schema_list_order: true
  # Direct bindings for pn-panel's pn-input. librime's key_binder select action switches
  # schemas directly — no menu, no intermediate state. F7/F8 do not exist on the k6
  # layout and cannot be pressed by a human; only pn-panel can synthesize them. We
  # originally drove the F4 menu (read cells, move cursor, space to commit). Every step
  # was a race. These two lines retired that whole machine.
  key_binder/bindings:
    - {when: always, accept: F7, select: luna_pinyin_tw}
    - {when: always, accept: F8, select: bopomofo_tw}
    # Tab cycles candidates, matching Mozc. RIME's native "next candidate" is Down — a
    # direction from the vertical era. The candidate strip here is laid out horizontally;
    # pressing Down to select the rightward item is a design artifact (the maintainer
    # noted we forced it to be horizontal). has_menu restricts the remapping to when
    # candidates exist; otherwise Tab behaves normally. A probe verified both schemas
    # work: Tab Tab space selects the third candidate.
    - {when: has_menu, accept: Tab, send: Down}
    - {when: has_menu, accept: "Shift+Tab", send: Up}
EOF

# Clear candidate labels for bopomofo. The schema defaults alternative_select_keys
# to ABCDEFGHIJ (uppercase), because the standard 1-9 keys are bopomofo symbols.
# The candidate strip labels read A B C D E, but the caps print bopomofo. The two
# do not align. iPad bopomofo has no selection keys; it is tapped. Each cell is
# already a button. The keys still work (Shift+A still selects the first), they
# are just not drawn.
cat > "$HOME/.config/ibus/rime/bopomofo_tw.custom.yaml" <<'EOF'
patch:
  menu/alternative_select_labels: [" ", " ", " ", " ", " ", " ", " ", " ", " ", " "]
EOF

# Horizontal candidates. This is the ibus-rime frontend's own configuration, not
# default.yaml and not the schema.
#
# 🔴 The location took two wrong turns. Documented to save the next person the time:
#      default.custom.yaml         → failed, ibus-rime ignores default.yaml's style
#      luna_pinyin_tw.custom.yaml  → failed, it ignores the schema's style too
#      ibus_rime.custom.yaml       → correct. /usr/share/rime-data/ibus_rime.yaml is
#                                    the frontend config, shipping horizontal: false;
#                                    the binary has the strings "ibus_rime.yaml" and
#                                    "style/horizontal" sitting next to each other.
#
#    How this was verified: we built an external IBus input context to catch
#    update-lookup-table and read table.get_orientation(). It was 2 (SYSTEM) before the
#    fix, and 0 (HORIZONTAL) after. GNOME's _candidateArea.setOrientation() groups
#    SYSTEM and VERTICAL together and draws vertically. The shell ignoring the setting
#    was an illusion. RIME had never set the value.
cat > "$HOME/.config/ibus/rime/ibus_rime.custom.yaml" <<'EOF'
patch:
  "style/horizontal": true
EOF

# build/ is the compiled cache. Changing custom.yaml without deleting this leaves the
# next boot on the old config.
rm -rf "$HOME/.config/ibus/rime/build" "$HOME/.config/ibus/rime/user.yaml"

# 🔴 Do not run rime_deployer --build by hand after deleting the cache.
#    That binary only builds schemas and default.yaml; it does not produce
#    build/ibus_rime.yaml. But it writes last_build_time in user.yaml when it finishes.
#    The frontend then sees no changes on startup and skips the maintenance pass that
#    would have generated the frontend config. The result is that build/ibus_rime.yaml
#    never exists, the engine falls back to the shared config (horizontal: false), and
#    the horizontal layout silently fails. Let the frontend deploy itself: restart ibus
#    and wait for it to build (about 20 seconds on this SoC).

echo "== [3] Input sources =="
# 🔴 The order carries two constraints. ('xkb','us') must be first: the terminal always
#    returns to it. Do not rely on an engine's internal alphanumeric mode. If Mozc
#    uses the Kotoeri keymap (see [4]), Ctrl+J/K/L collide with readline's return, kill
#    to end of line, and clear screen. This entire OSK was built for the terminal.
#
#    The remaining two are JP then TW, so pn-input cycles US → JP → TW → US.
#    A-Z is something you can hold in your head; "frequency of use" is not.
# 🔴 Japanese uses mozc-on, not mozc-jp. mozc-jp starts in direct-input mode, where
#    typing romaji outputs latin letters (it looks exactly like a broken installation).
#    The k6 layout has no hankaku/zenkaku key to get out of it. mozc-on (Mozc:あ) starts
#    in kana. This is the same split macOS makes between かな and 英数.
gsettings set org.gnome.desktop.input-sources sources \
  "[('xkb','us'),('ibus','mozc-on'),('ibus','rime')]"

# GTK_IM_MODULE and XMODIFIERS do not need to be set under GNOME. The Wayland shell
# is the IM. ibus-daemon is brought up by org.freedesktop.IBus.session.GNOME.service
# with the session (the ibus package links it into gnome-session.target.wants).

echo "== [3a] Other CJK languages (optional, omitted from sources by default) =="
# The maintainer does not use these two, but this keyboard often serves other CJK users.
# The engines are installed and the pn-panel labels are ready; anyone who needs them
# is one gsettings line away. An engine working while its label is missing is the
# hardest kind of failure to debug, so the labels are present unconditionally.
#
# Both take US keysyms, so the k6 layout needs no changes:
#   chewing (bopomofo) declares layout=us and maps the US keysyms to bopomofo itself.
#   hangul (Korean) declares layout=kr. _composeLayout lacks a kr-extended and falls
#          back to us-extended, and Korean 2-set is typed with latin keys anyway.
#
# 🔴 Bopomofo's default path is RIME's bopomofo_tw (see [2] above), not chewing. chewing
#    stays for people used to the Microsoft Bopomofo behavior (it converts silently
#    and asks only on arrow-down). To use it, run `pn ime add chewing`. Both paths
#    print bopomofo on the caps.
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y ibus-hangul ibus-chewing

# chewing is the Microsoft Bopomofo lineage: it converts silently into the preedit
# and asks only on arrow-down. iPad hands (the maintainer's) think it is broken.
# space-as-selection brings up candidates when space is pressed at the end. That
# gives iPad hands an exit while keeping chewing's phrase model intact (plain-zhuyin
# would discard it, so it stays off). chi-eng-mode-toggle defaults to caps_lock, which
# fights our Caps→US binding. Change it to shift.
gsettings set org.freedesktop.IBus.Chewing space-as-selection true
gsettings set org.freedesktop.IBus.Chewing chi-eng-mode-toggle "shift"
gsettings set org.freedesktop.IBus.Chewing show-systray false
# Caps: when switched to chewing, pn-osk labels every cell of k6 as standard bopomofo
# (PN_BOPOMOFO). The strings are untouched and the sent keys remain the same. The
# standard bopomofo keyboard is just a US keyboard with a second symbol per key.

# To put them in the cycle, add them (the order is pn-input's tap cycle):
#
#   gsettings set org.gnome.desktop.input-sources sources \
#     "[('xkb','us'),('ibus','rime'),('ibus','chewing'),('ibus','mozc-on'),('ibus','hangul')]"
#
# ⚠️ Five sources on one button means four taps to the far end. The maintainer kept
# the original three short on purpose.
#
# Bopomofo could also go through RIME (rime-data-bopomofo is already present via
# librime-data, with bopomofo, bopomofo_tw, and bopomofo_express schemas), but then
# it would share the single `rime` engine with pinyin and need Ctrl+` to switch
# schemas. The k6 portrait layout has no backtick. The independent chewing engine is
# the right choice for this device.

echo "== [3b] IBus registry cache =="
# Rebuild once after installing new engines, as mozc's own component XML recommends.
# It is cheap and harmless.
#
# 🔴 Misattribution correction (2026-08-18): This once read "if not rebuilt, gsettings
#    sees the source and the panel can switch to it, but typing does nothing." The
#    symptom was real, but the cause was not this. Measured, `ibus list-engine`
#    lists rime and mozc-jp even before write-cache. The real cause was selecting the
#    wrong engine (mozc-jp starts in direct-input mode, see [3] above), unrelated to
#    the cache. Keep this step, but stop using it to explain that symptom.
ibus write-cache || true
ibus restart 2>/dev/null || true

echo "== [3c] Two physical keyboard keys =="
# The behavior lives in pn-panel's _pnInstallKeybindings (which hijacks these two
# bindings, replacing the MRU cycle with a list-order cycle). Only the accel is
# written here.
#
# Ctrl+Space → cycles US → JP → TW → US (order comes from the sources above)
gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Control>space']"
# Caps → returns to US (if already on US, goes back to the previous source, like macOS)
gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "['Menu']"

# 🔴 Caps itself must first become a pressable key. It is natively a locking modifier
#    and has no bindable keysym, so mutter never receives it. caps:menu makes it send
#    Menu and drops the locking behavior. Menu has no other use on this device (the k6
#    layout has no such key).
#
#    Verify the option actually exists in this device's xkeyboard-config before setting
#    it blindly:
if grep -qE '^\s*caps:menu\b' /usr/share/X11/xkb/rules/evdev.lst; then
  # 🔴 Append it. setup.sh also puts altwin:swap_lalt_lwin (Mac keyboard) into this
  #    key, and overwriting the array would destroy it.
  python3 - <<'PY'
import subprocess, ast
cur = ast.literal_eval(subprocess.check_output(["gsettings","get","org.gnome.desktop.input-sources","xkb-options"], text=True).strip())
if "caps:menu" not in cur:
    cur.append("caps:menu")
subprocess.check_call(["gsettings","set","org.gnome.desktop.input-sources","xkb-options", repr(cur)])
print("   xkb-options =", cur)
PY
else
  echo "   ⚠️ This device's xkeyboard-config lacks caps:menu, the Caps key will have no effect."
  echo "      Available candidates: grep -E '^\s*caps:' /usr/share/X11/xkb/rules/evdev.lst"
  echo "      Pick one that emits a true keysym without locking, then change the accel line above."
fi
# ⚠️ Pending verification: the caps lock key on pn-osk should be unaffected. It is
#    a shell-side level latch, not the Caps_Lock keysym. That claim has not yet been
#    tested on the glass.

cat <<'EOF'

== [4] One step is left, and it has to be done on the glass ==

Set Mozc's keymap to Kotoeri. On the device, run:

    /usr/lib/mozc/mozc_tool --mode=config_dialog

    -> キー設定の選択 / Keymap style -> Kotoeri

Kotoeri gives you Ctrl+J for ひらがな, Ctrl+K for カタカナ and Ctrl+L for 英数,
and the k6 layout has all three. The default MS-IME keymap uses F6/F7/F8 and a
hankaku/zenkaku key, none of which exist on this keyboard -- without the change
the only way to reach katakana is paging down the candidate list with Space.

Why the script does not do it: the keymap lives in ~/.config/mozc/config1.db, a
binary protobuf, and there is no supported text config or command-line switch
that writes it. Editing that file blind is more dangerous than one manual click.
(mozc-utils-gui is a dependency of ibus-mozc and is already installed, so there
is no extra Qt download.)

EOF

# ── Japanese JIS keyboard ───────────────────────────────────────────────────────
# Deliberately absent, and recommended to stay that way. The reasons are split:
#
#   Physical JIS keyboard — requires nothing from this repository. Add an xkb source:
#       ('xkb','jp')
#     mozc remains the same engine; only the keymap changes.
#
#   JIS layout for the on-screen keyboard — means maintaining a second composed
#     layout. This repository's stance is that one layout for both orientations beats
#     two tuned ones (see the keyboard section in the README). Across languages this
#     rule is even stronger: pinyin, bopomofo, romaji, Korean 2-set, and English all
#     consume the same 26 letters. One k6 layout covers them all. An exception for JIS
#     only buys muscle memory for JIS key positions on the glass. The glass has no
#     tactile feedback, which is the only selling point of a physical JIS keyboard.
#
# Most Japanese users type romaji on computers (the maintainer included). The demand
# for direct kana input via JIS is even lower on this device.

echo "ime.sh done — log in again or systemctl restart gdm3 to apply"
